{
    'name': 'project task recurrency',
    'version': '12.0.0.1',
    'category': 'Projects',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Serincloud',
    'depends': [
        'project',

    ],
    'data': [
        'data/rec_task_action.xml',
        'views/project_task_rec_view.xml',
    ],
    'installable':True,
}
